import { CardData } from './types';

export const CARDS: CardData[] = [
  {
    id: 'card-1',
    clientName: 'LUMIN8 AGENCY',
    projectTitle: 'Scaling a Distributed Global Growth Engine',
    years: '2020 – Present',
    tags: ['Growth Strategy', 'AI Operations', 'Agency Leadership'],
    image: 'https://via.placeholder.com/800x600?text=Lumin8+Agency',
    imageAlt: 'Dashboard interface showing lead volume trend line and global team network map.',
    link: 'https://lumin8.agency',
    themeColor: '#0055FF',
    rotation: -4,
  },
  {
    id: 'card-2',
    clientName: 'SPORTBALL',
    projectTitle: 'Digital Transformation & CAC Reduction (-67%)',
    years: '2023 – 2024',
    tags: ['Franchise Growth', 'Performance Marketing', 'Analytics'],
    image: 'https://via.placeholder.com/800x600?text=Sportball',
    imageAlt: 'Split-screen comparison showing old high cost vs new low cost metrics.',
    link: 'https://sportball.com',
    themeColor: '#FF4500',
    rotation: 3,
  },
  {
    id: 'card-3',
    clientName: 'DIGITAL CORPORATE REPORTING',
    projectTitle: 'Interactive Financial Storytelling (React + D3.js)',
    years: '2024 – Present',
    tags: ['Data Visualization', 'Investor Relations', 'Creative Tech'],
    image: 'https://via.placeholder.com/800x600?text=Digital+Corporate+Reporting',
    imageAlt: 'Laptop screen displaying an interactive scrollytelling annual report with complex data visualization.',
    link: 'https://reports.tafsik.com',
    themeColor: '#4B0082',
    rotation: -2,
  },
  {
    id: 'card-4',
    clientName: 'NABORINO',
    projectTitle: 'Bootstrapping a Hyperlocal Commerce Marketplace',
    years: '2020 – 2023',
    tags: ['Product Marketing', 'Community Building', 'PR Strategy'],
    image: 'https://via.placeholder.com/800x600?text=Naborino',
    imageAlt: 'Collage of mobile app screens for a group buying interface against blurred media logos.',
    link: '#/case-study-details',
    themeColor: '#008B8B',
    rotation: 5,
  },
  {
    id: 'card-5',
    clientName: 'MERCKU',
    projectTitle: 'Global Go-To-Market for Consumer Hardware',
    years: '2019 – 2020',
    tags: ['E-Commerce', 'Global Strategy', 'Consumer Tech'],
    image: 'https://via.placeholder.com/800x600?text=Mercku',
    imageAlt: 'Product shot of Wi-Fi hardware next to tablets showing Shopify and HubSpot dashboards.',
    link: '#/case-study-details',
    themeColor: '#4682B4',
    rotation: -3,
  },
  {
    id: 'card-6',
    clientName: 'AMD (GPUOPEN)',
    projectTitle: 'Building an Open-Source Developer Community',
    years: '2018',
    tags: ['DevRel', 'Open Source', 'Tech Marketing'],
    image: 'https://via.placeholder.com/800x600?text=AMD+GPUOpen',
    imageAlt: 'Stylized graphic illustrating a GPU chip schematic merging with code syntax.',
    link: '#/case-study-details',
    themeColor: '#B22222',
    rotation: 2,
  },
  {
    id: 'card-7',
    clientName: 'METAVRSE',
    projectTitle: 'Pioneering Enterprise VR/AR Solutions',
    years: '2016 – 2018',
    tags: ['VR/AR', 'B2B Sales', 'Innovation'],
    image: 'https://via.placeholder.com/800x600?text=Metavrse',
    imageAlt: 'Futuristic wireframe of a 3D virtual showroom environment viewed through a VR headset.',
    link: '#/case-study-details',
    themeColor: '#C71585',
    rotation: -5,
  },
  {
    id: 'card-8',
    clientName: 'BELL CANADA',
    projectTitle: 'Social Data Strategy & Customer Care',
    years: '2012 – 2016',
    tags: ['Social Analytics', 'Customer Experience', 'Telecom'],
    image: 'https://via.placeholder.com/800x600?text=Bell+Canada',
    imageAlt: 'Network analysis data visualization showing social conversation flows and reduced churn indicators.',
    link: '#/case-study-details',
    themeColor: '#006400',
    rotation: 4,
  },
  {
    id: 'card-9',
    clientName: 'TRINDENT CONSULTING',
    projectTitle: 'Operational Efficiency & Process Redesign ($2M Savings)',
    years: '2011 – 2012',
    tags: ['Operations', 'Six Sigma', 'Process Optimization'],
    image: 'https://via.placeholder.com/800x600?text=Trindent+Consulting',
    imageAlt: 'Complex industrial process map transforming into a simplified, streamlined flow chart.',
    link: '#/case-study-details',
    themeColor: '#36454F',
    rotation: -1,
  },
  {
    id: 'card-10',
    clientName: 'ROSENZWEIG & CO.',
    projectTitle: 'C-Suite Executive Search & Operations',
    years: '2010 – 2011',
    tags: ['Talent Strategy', 'Operations', 'HR Tech'],
    image: 'https://via.placeholder.com/800x600?text=Rosenzweig+Co',
    imageAlt: 'Stylized organizational chart with the top C-Suite tier highlighted in gold.',
    link: '#/case-study-details',
    themeColor: '#DAA520',
    rotation: 3,
  },
  {
    id: 'card-11',
    clientName: 'LEGAL PRACTICE',
    projectTitle: 'Litigation, Risk Management & Commercial Law',
    years: '2007 – 2009',
    tags: ['Legal Strategy', 'Risk Mitigation', 'Negotiation'],
    image: 'https://via.placeholder.com/800x600?text=Legal+Practice',
    imageAlt: 'Minimalist abstract wireframe rendering of a legal contract and a fountain pen.',
    link: '#/case-study-details',
    themeColor: '#191970',
    rotation: -4,
  },
  {
    id: 'card-12',
    clientName: 'JEWISH COMMUNITY LEADERSHIP',
    projectTitle: 'Crisis Leadership & Community Mobilization',
    years: '2023 – Present',
    tags: ['Crisis Comms', 'Advocacy', 'Non-Profit'],
    image: 'https://via.placeholder.com/800x600?text=Jewish+Community',
    imageAlt: 'Abstract network map showing thousands of connected individuals representing rapid mobilization.',
    link: '#/case-study-details',
    themeColor: '#A0522D',
    rotation: 2,
  },
  {
    id: 'card-13',
    clientName: 'HUMBER COLLEGE',
    projectTitle: 'Teaching the Next Gen of Marketers',
    years: '2023 – 2024',
    tags: ['Education', 'AI & Analytics', 'Mentorship'],
    image: 'https://via.placeholder.com/800x600?text=Humber+College',
    imageAlt: 'Modern lecture hall whiteboard filled with diagrams connecting Generative AI to marketing analytics.',
    link: '#/case-study-details',
    themeColor: '#4169E1',
    rotation: -2,
  },
];
